//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.16 at 01:08:07 PM AST 
//


package TaskModule2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Greenhouse }
     * 
     */
    public Greenhouse createGreenhouse() {
        return new Greenhouse();
    }

    /**
     * Create an instance of {@link Greenhouse.Plant }
     * 
     */
    public Greenhouse.Plant createGreenhousePlant() {
        return new Greenhouse.Plant();
    }

    /**
     * Create an instance of {@link Greenhouse.Plant.GrowingTips }
     * 
     */
    public Greenhouse.Plant.GrowingTips createGreenhousePlantGrowingTips() {
        return new Greenhouse.Plant.GrowingTips();
    }

    /**
     * Create an instance of {@link Greenhouse.Plant.VisualParameters }
     * 
     */
    public Greenhouse.Plant.VisualParameters createGreenhousePlantVisualParameters() {
        return new Greenhouse.Plant.VisualParameters();
    }

    /**
     * Create an instance of {@link Greenhouse.Plant.Multiplying }
     * 
     */
    public Greenhouse.Plant.Multiplying createGreenhousePlantMultiplying() {
        return new Greenhouse.Plant.Multiplying();
    }

    /**
     * Create an instance of {@link Greenhouse.Plant.GrowingTips.Temperature }
     * 
     */
    public Greenhouse.Plant.GrowingTips.Temperature createGreenhousePlantGrowingTipsTemperature() {
        return new Greenhouse.Plant.GrowingTips.Temperature();
    }

    /**
     * Create an instance of {@link Greenhouse.Plant.GrowingTips.Watering }
     * 
     */
    public Greenhouse.Plant.GrowingTips.Watering createGreenhousePlantGrowingTipsWatering() {
        return new Greenhouse.Plant.GrowingTips.Watering();
    }

}
