//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.16 at 01:52:53 PM AST 
//

package TaskModule2;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryAuto {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 * 
	 */
	public ObjectFactoryAuto() {
	}

	/**
	 * Create an instance of {@link GreenhouseAuto }
	 * 
	 */
	public GreenhouseAuto createGreenhouse() {
		return new GreenhouseAuto();
	}

	/**
	 * Create an instance of {@link GreenhouseAuto.Plant }
	 * 
	 */
	public GreenhouseAuto.Plant createGreenhousePlant() {
		return new GreenhouseAuto.Plant();
	}

	/**
	 * Create an instance of {@link GreenhouseAuto.Plant.GrowingTips }
	 * 
	 */
	public GreenhouseAuto.Plant.GrowingTips createGreenhousePlantGrowingTips() {
		return new GreenhouseAuto.Plant.GrowingTips();
	}

	/**
	 * Create an instance of {@link GreenhouseAuto.Plant.VisualParameters }
	 * 
	 */
	public GreenhouseAuto.Plant.VisualParameters createGreenhousePlantVisualParameters() {
		return new GreenhouseAuto.Plant.VisualParameters();
	}

	/**
	 * Create an instance of {@link GreenhouseAuto.Plant.Multiplying }
	 * 
	 */
	public GreenhouseAuto.Plant.Multiplying createGreenhousePlantMultiplying() {
		return new GreenhouseAuto.Plant.Multiplying();
	}

	/**
	 * Create an instance of
	 * {@link GreenhouseAuto.Plant.GrowingTips.Temperature }
	 * 
	 */
	public GreenhouseAuto.Plant.GrowingTips.Temperature createGreenhousePlantGrowingTipsTemperature() {
		return new GreenhouseAuto.Plant.GrowingTips.Temperature();
	}

	/**
	 * Create an instance of {@link GreenhouseAuto.Plant.GrowingTips.Watering }
	 * 
	 */
	public GreenhouseAuto.Plant.GrowingTips.Watering createGreenhousePlantGrowingTipsWatering() {
		return new GreenhouseAuto.Plant.GrowingTips.Watering();
	}

}
